<a href="https://colab.research.google.com/github/Coding-Matrix/NumPy-Basics-2/blob/master/NumpyBasics2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Basics #2 Colab**


Created By Coding Matrix On Youtube. https://www.youtube.com/channel/UCKaajyjktvduM6mmuBtAOyg

The first thing that we need to do before we start is to **import numpy**, and we will do import it as np. 


In [0]:
import numpy as np

# Using the `np.arange` Function
Using np.array to create arrays manually can cosume a lot of time since it was hardcoded. When you have many values in an array, Numpy provides a very useful function which acts in a very similar way as the range function in python. `np.arange` will return an array of evenly spaced values within a given interval. The code below shows how to use this function. 

In [0]:
scalararray = np.arange(7)
print(repr(scalararray))

array([0., 1., 2., 3., 4., 5., 6., 7.])


In the example we use a scalar. A scalar is single value such as integer, float, etc. To read more about this head over to https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.scalars.html. When one argument is passed or a scalar value is passed, `np.arange` will return evenly spaced values from the default value of 0 and all the way **UP T0** the number specified but not including it, meaning the lower end is inclusive while the upper end is not.

In [0]:
array2 = np.arange(1, 5, dtype=float )
print(repr(array2))

array([1., 2., 3., 4.])


The code shows that the `np.arange` function allows for manual casting using the `dtype` keyword argument. When two argument are passed the first argument is the start of the range and the second argument is the stop of the the function. Again, the lower end is inclusive while the upper end is exclusive.

In [0]:
array3 = np.arange(start=1, stop=6, step=2)
print(array3)

[1 3 5]


When three arguments are passed, the first argument is the start of the range, the second argument is the stop of the range while the third argument is the step of the range. Like Python's range function the step refers to amount you go up by or the spacing between the start and the stop values. If the step is not specified, the default step is one.

The code above shows the use of np.arange. Notice how the output of the arrays is always a 1-D array. 

# Using the `np.linspace` Function

`np.linspace` is very similar to `np.arange` but is used when you want to specify the number of elements in the returned array rather than step size. The `np.linspace`function will create evenly spaced sequences of numbers in a format of a Numpy array. The function takes two required arguments which are the start and the end of the range. Check out the code below to get a deeper understanding of the code.


In [0]:
linspacearr = np.linspace(1,10)
print(repr(linspacearr))

This is probably not what you were expecting. There are two things to note here. 

1: The end of the range is INCLUSIVE in `np.linspace` while in `np.arange` it is not. This is only true if the keyword argument `endpoint` is not set to `endpoint=False`

2: `np.linspace` creates evenly spaced sequences of numbers between two numbers. If we want to specify the number of elements, we use the `num` keyword argument. In the example we did not use the `num` keyword so the default 50 evenly spaced values were outputted in a 1-D array.

Another thing to note is that np.linspace allows for manual casting using the `dtype` keyword argument. 

Let's Check this out in the code below:

In [0]:
endpointarr = np.linspace(1, 10, endpoint=False)
print(repr(endpointarr))

As you can see when the `endpoint=False` the end of the range is **Exclusive**.

---





In [0]:
spacedarr = np.linspace(1, 10, num=5)
print(repr(spacedarr))

In the example, `spacedarr` only outputs **5** evenly spaced values because the `num` keyword is set to 5.

In [0]:
castedarr = np.linspace(1, 10, num=5, dtype=int)
print(repr(castedarr))

When we perform manual casting, it can sometimes skew the data in the way that the numbers are not evenly spaced. In the example above, we use the `dtype` keyword argument to manually cast the output array to an `int` whereas before would automatically switch to the data type needed to be evenly spaced.


# Using `.ndim` Property and `.shape` Property


The shape of an array is the number of elements in each dimension and the shape property returns a **tuple** of array dimensions. Let's walk through array shapes in depths going from simple 1D arrays to more complicated 2D and 3D arrays.


In [0]:
oned = np.array([1, 2, 3])
print(repr(oned.ndim))
print(repr(oned.shape))

Let’s start with this 1-D array and the dimensions of a 1-dimensional array can just be described as the number of elements in the 1-Dimensional array. In the example, We have a 1-dimensional array from values 1 to 5 inclusive and the shape for this array would just be 5 because there is only one dimension and the shape of an array is the number of elements in each dimension. The `.ndim` property will return the number of dimensions of the array and the `.shape `property will return a tuple of array dimensions. 


When we run the code cell and for the `.shape` property generates a one-element tuple with a comma beside it. When generating a one-element tuple, if you write only one object in parentheses (), the parentheses () are ignored and not considered a tuple. The reason why you need a comma , for a single tuple is that "tuple is an object delimited by comma ,", not "an object enclosed in parentheses ()"


In [0]:
twod = np.array([[1, 2 ,3], 
                 [1, 2, 3]])
print(repr(twod.ndim))
print(repr(twod.shape))

For a 2-dimensional array, the dimensions are described as by the number of rows by the number of columns. In our example the dimensions of the array are 3 by 3. The shape of this array would be described as 3 rows and 3 columns. The shape of the array is going to be a the tuple (3,3) where the first number is the rows and the second number is columns.


In [0]:
threed = np.array([[[1, 2, 3], 
                    [1, 2, 3]], 
                   
                   [[1, 2, 3], 
                    [1, 2, 3]]])
print(repr(threed.ndim))
print(repr(threed.shape))

For a 3-dimensional array, an array that has 2-D arrays as its elements or 3 nested levels of arrays, one for each dimension. The dimensions are described as by the layers/depth, and the number of rows and columns in each layer or depth. In our example, the shape of this array is 2 layers, 2 rows, and 3 columns and the dimensions of this array is 2 by 3 by 3. The `shape` property will return the tuples (2, 3, 3), where the first number is the layers, the second number is the rows, the third number is the Columns. Note that the rows and columns in each layer have to be the same.


# Using the `np.reshape` Function to Reshape Data

Reshaping Data is just as the name implies changing the shape of an array to a new one. The function we use to do so is the np.reshape function which take two required arguments which an array and the new dimensions of the array. 

In [0]:
unshaped = np.arange(8)
print(repr(unshaped))

The code above will return a 1-D array from value 1 to 8 but not inclusing 8.

In [0]:
reshaped = np.reshape(unshaped, (4, 2))
print(repr(reshaped))

In the code above, we use the `np.reshape` function to reshape the array `unshaped` to a 2-D array that has 4 rows and 2 columns. Note that the new shape must exactly contain all the elements from the input array. The product of the dimensions have to be equal to the amount of the elements in the array we wish to reshape. For example, the array `unshaped` has 8 elements and the dimensions we wish to reshape it to (4, 2). 4 x 2 = 8. 




In [0]:
unshaped2 = np.array([[1, 2, 3], [1, 2, 3]])
print(repr(unshaped2))

The code above is a 2-D array that was created using the np.array function. The dimensions of this 2-D array is 2 rows by 3 columns. 

In [0]:
reshaped2 = np.reshape(unshaped2, (1, 2, -1))
print(repr(reshaped2))
print(repr(reshaped2.shape))

In the code above, we use the reshape function to reshape the array, `unshaped2. Notice we want to reshape it to a 3-D array but we have a -1 as one of it's dimensions. We are allowed to use the special value of -1 in at most one dimension of the new shape. The dimension with -1 will take on the value necessary to allow the new shape to contain all the elements of the array. The new shape will be whatever value is neccessary to contain all the elemnets in the array. 

# Using the np.flatten Function

We can flatten an array using the np.flatten function. While the np.reshape function can perform any reshaping utilities we need, falttening data is done very often so NumPy has Provided it for us. Flattening an array reshapes it into a 1D array.

In [0]:
print(repr(unshaped2.flatten()))
print(repr(unshaped2))

We used the previous array we used, unshaped2 which was a 2-D array and the output of the code will be a 1-D array. Weput the name of the array followed by `.flatten()` to flatten any array we wish to. 

# Using the np.transpose Function. 

We can also transpose our data which means it causes (two or more things) to change places with each other and in our case it is arrays. The function takes in a required argument, which will be the array we want to transpose. 

In [0]:
newarray = np.arange(6).reshape((2,3))
print(repr(newarray))
print(repr(newarray.shape))

We created a 1-D array using the np.arange function and the we reshaped the data using the reshape function and instead of creating and instead of creating a new varibale and adding the two required arguments, the input array and the dimensions, when we create an array we use the function like `.reshape()` and input the dimensions we want to array to be reshaped to. 

In [0]:
transposed = np.transpose(newarray)
print(repr(transposed))
print(repr(transposed.shape))

In the code above, we transposed the data which means we switch the dimensions for the input array. For a 2-D array the number of rows will become the number of columns and the number of columns will we the number of rows. The shape of `newarray` is (2, 3) but when we transpose it the shape of the array becomes (3, 2)

It also has a single keyword argument called axes, which represents the new permutation of the dimensions. The permutation is a tuple/list of integers, with the same length as the number of dimensions in the array. It tells us where to switch up the dimensions. The axes keyword is very similar to the dimesnions of an array. For example, for a 2-d array axis=0 is the rows, axis=1 is equal to the columns and for a 3-d array axis=0 is the layers, axis=1 is the rows and axis=3 is the columns. For this lesson that is all you need to know. Later on in the course we will take a deeper look at axes of an array. Take a look at the code below for better understanding.


In [0]:
permutation = np.arange(24).reshape(3, 2, 4)
print(repr(permutation))
print(repr(permutation.shape))

We created a 1-D array and reshaped it to a 3-D array with 3 layers, 2 rows and 3 columns. 

In [0]:
axes = np.transpose(permutation, axes=(2,1,0))
print(repr(axes))
print(repr(axes.shape))

We transpose the array `permutation` and change it's permutation meaning it's arrangment using the `axes` keyword argument. For a 3-D array, `axes` 2 means the columns, so the number of columns in the inputted array becomes the layers, axes 1 means the rows so the rows, so the number of rows in the inputted array becomes the rows and `axes` 0 means the layers, so the number of layers in the outputted array become the columns. The shape of the inputted array, permutation is (3, 2, 4) and the shape of the transposed array is (4, 2, 3).

# Using the `np.zeros` and `np.ones` Function

Sometimes, we need to create arrays filled solely with 0 or 1. For creating these arrays, NumPy provides the functions `np.zeros` and `np.ones`. They both take one required argument which is the array shape. The functions also allow for manual casting using the dtype keyword argument.

In [0]:
zeros = np.zeros((4, 2), dtype=int)
print(repr(zeros))

A 2-D array with all zeroes and 4 rows and 2 columns has been created using the `np.zeros` function. Using the `dtype` keyword argument, we manually cast the array to all integers. 

In [0]:
ones = np.ones((1, 2, 3))
print(repr(ones))

A 3-D array with all ones and 1 layer, 2 rows and 3 columns has been created using the `np.ones` function. The outut will be all floats since we have not specified the data type of the array. 

If we want to create an array of 0's or 1's with the same shape as another array, we can use functions `np.zeros_like` and `np.ones_like`.

In [0]:
newarr = np.arange(8)
print(repr(newarr))

We created a 1-D array using the np.arange function and the values returns an array from values 1 to 8 but not including 8. 

In [0]:
zeros2 = np.zeros_like(newarr)
print(repr(zeros2))

The np.zeros_like will output an array of zeros with the same shape as `newarr` which has a shape of (8,) becasue this is the array we inputted as the argument for the function.

In [0]:
newarr2 = np.arange(24).reshape(6,4)
print(repr(newarr2))

We created a 1-D array from 0 to 24 but not including 24 and we reshaped the array to be a 2-D array with 6 rows and 4 columns. 

In [0]:
ones2 = np.ones_like(newarr2)
print(repr(ones2))

The np.ones_like will output an array of ones with the same shape as `newarr2` which has a shape of (6,4) becasue this is the array we inputted as the argument for the function.